RetailDevGit/src/objects/ARM_Brand__c.object
<CustomObject>
    <description>Appirio Retail Management (ARM) Object</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ARM Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RetailDevGit/src/objects/ARM_Brand_Image__c.object
<CustomObject>
    <description>Appirio Retail Management (ARM) Object</description>
    <fields>
        <fullName>Image_Type__c</fullName>
        <inlineHelpText>Maximum Recommended Size (w*h) for:
Banner - 520px * 200px
Logo - 635px * 150px
Mobile Banner Logo - 200px * 150px  
Mobile Logo -  200px * 140px</inlineHelpText>
        <label>Image Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Banner</fullName>
                </value>
                <value>
                    <fullName>Logo</fullName>
                </value>
                <value>
                    <fullName>Mobile Logo</fullName>
                </value>
                <value>
                    <fullName>Mobile Banner Logo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>define that this image is active to be used by the side for parent brand</description>
        <inlineHelpText>If unchecked, the attached image will not be used in the site</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Retail_Function__c</fullName>
        <label>Retail Function</label>
        <referenceTo>ARM_Retail_Function__c</referenceTo>
        <relationshipLabel>Brand Images</relationshipLabel>
        <relationshipName>Brand_Images</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Brand Image</label>
    <nameField>
        <displayFormat>BI-{0000}</displayFormat>
        <label>Brand Images Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Images</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RetailDevGit/src/objects/ARM_Navigation_Item__c.object
<CustomObject>
    <description>Appirio Retail Management (ARM) Object. This object stores all the navigation items related to its parent functions.</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <inlineHelpText>eg. &quot;HOME&quot;. The name provided here will be the displayed name of navigation item on the site</inlineHelpText>
        <label>Display Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Defines the state of Navigation Item record</description>
        <inlineHelpText>If unchecked, the navigation item will not reflect in the site</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Page_URL__c</fullName>
        <inlineHelpText>Usually starts with /s/ where &apos;/s/&apos; being the home page. Note that name of pages is case sensitive.
eg. /s/mycases - in this case mycases page should be defined in community (lightning bolt) as a flexipage.</inlineHelpText>
        <label>Page-URL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Function__c</fullName>
        <label>Retail Function</label>
        <referenceTo>ARM_Retail_Function__c</referenceTo>
        <relationshipLabel>Navigation Items</relationshipLabel>
        <relationshipName>Navigation_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Navigation Item</label>
    <nameField>
        <displayFormat>NI-{00000}</displayFormat>
        <label>Navigation Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Navigation Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RetailDevGit/src/objects/ARM_Question__c.object
<CustomObject>
    <description>Appirio Retail Management (ARM) Object</description>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Count</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Select</fullName>
                </value>
                <value>
                    <fullName>Multi-Select</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <description>Survey header object</description>
        <inlineHelpText>Survey header object</inlineHelpText>
        <label>Survey</label>
        <referenceTo>ARM_Survey__c</referenceTo>
        <relationshipName>ARM_Question</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ARM Survey Question</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RetailDevGit/src/objects/ARM_Retail_Function__c.object
<CustomObject>
    <description>Appirio Retail Management (ARM) Object.
        This object stores the data for various retail functions used in salesforce bolt community cloud</description>
    <label>Retail Function</label>
    <nameField>
        <label>Retail Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RetailDevGit/src/objects/ARM_Sub_Navigation_Item__c.object
<CustomObject>
    <description>Appirio Retail Management (ARM) Object</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <inlineHelpText>eg. &quot;HOME&quot;. The name provided here will be the displayed name of sub navigation item.</inlineHelpText>
        <label>Display Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Defines the state of Sub Navigation Item record</description>
        <inlineHelpText>If unchecked, this will not get reflected in the site</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Navigation_Item__c</fullName>
        <label>Navigation Item</label>
        <referenceTo>ARM_Navigation_Item__c</referenceTo>
        <relationshipLabel>Sub Navigation Items</relationshipLabel>
        <relationshipName>Sub_Navigation_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Page_URL__c</fullName>
        <inlineHelpText>Usually starts with /s/ where &apos;/s/&apos; being the home page. Note that name of pages is case sensitive.
eg. /s/mycases - in this case mycases page should be defined in community (lightning bolt) as a flexipage.</inlineHelpText>
        <label>Page-URL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Sub Navigation Item</label>
    <nameField>
        <displayFormat>SNI-{0000}</displayFormat>
        <label>Sub Navigation Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sub Navigation Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RetailDevGit/src/objects/ARM_Survey__c.object
<CustomObject>
    <description>Appirio Retail Management (ARM) Object</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Survey end date</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Survey start date</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Survey_Type_Editable__c</fullName>
        <description>Product surveys have a barcode scan and can loop through and answer questions about many products; Non-product surveys do NOT have a barcode scan.</description>
        <inlineHelpText>Product surveys have a barcode scan and can loop through and answer questions about many products; Non-product surveys do NOT have a barcode scan.</inlineHelpText>
        <label>Survey Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scan</fullName>
                </value>
                <value>
                    <fullName>Non Scan</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TDLinx_Acct_Level_E__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TDLinx Acct Level E</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ARM_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retailDev/src/classes/ARM_Retail_Test_Utils.cls
/**=====================================================================
 * (c) 2017 Appirio - A Wipro Company, Inc
 * Name: ARM_Retail_Test_Utils
 * Description: Utility class for Test data
 * Created Date: Mar 03, 2017
 * Created By: Gaurav Gupta (Appirio - A Wipro Company)
 * 
 * Date Modified      Modified By                  Description of the update

*  =====================================================================*/
@isTest
public with sharing class ARM_Retail_Test_Utils /* TODO : Rename class to ARM_Test_Utils */ {
   
   
  //insert Account
  public static Account insertAccount(Boolean isInsert) {
    Account defaultAccount = new Account();
    defaultAccount.Name = 'Test Account'+randomNumber();
    if(isInsert) {
      insert(defaultAccount);
    }
    return defaultAccount;
  }
   
  //insert Contact
  public static Contact insertContact(Id accountId, Boolean isInsert){
    Contact contact = new Contact(MailingCountry='USA',MailingState='TX',MailingCity='Dallas',
                                  FirstName='firstname'+randomNumber(),Salutation='Mr.',LastName='test'+randomNumber(),
                                  email='test@'+randomNumber()+'test.com' , AccountId = accountId);
    if(isInsert) {                                  
      insert(contact);
    }
    return contact;
  }
  
  //insert attachments
  public static Attachment insertAttachment(Id parentId, String name, Boolean isInsert){
        Attachment attach=new Attachment();   	
    	attach.Name ='Unit Test Attachment';
    	Blob bodyBlob = Blob.valueOf('Unit Test Attachment Body');
    	attach.body = bodyBlob;
        attach.parentId = parentId;

    if(isInsert) {                                  
      insert(attach);
    }
    return attach;
  }
  
  //insert Brand Image
  public static ARM_Brand_Image__c insertAccountContactRole(ARM_Retail_Function__c test_RetailFunction, String imageType, Boolean isInsert){
    ARM_Brand_Image__c test_BrandImage = new ARM_Brand_Image__c (Image_Type__c = imageType,
                                                                 Retail_Function__c = test_RetailFunction.Id,
                                                                 Is_Active__c = true);

    if(isInsert) {                                  
      insert(test_BrandImage);
    }
    return test_BrandImage;
  }
  
  
  //insert AccountContactRole
  public static AccountContactRole insertAccountContactRole(Id accountId, Id contactId, Boolean isInsert){
    AccountContactRole test_AccountContactRole = new AccountContactRole (AccountId = accountId,
                                                                         ContactId = contactId);
    if(isInsert) {                                  
      insert(test_AccountContactRole);
    }
    return test_AccountContactRole;
  }
   
    
  //insert Sub Navigation Item
  public static ARM_Sub_Navigation_Item__c insertSubNavigationItemn(ARM_Navigation_Item__c test_NavigationItem, String displayName, String pageURL, Boolean isInsert){
      
    //ARM_Navigation_Item__c test_NavigationItem = insertNavigationItemn('Advocacy' , '/s/advocacy-center' , true);
    ARM_Sub_Navigation_Item__c test_SubNavigationItem = new ARM_Sub_Navigation_Item__c (Navigation_Item__c = test_NavigationItem.Id,
                                                                                        Display_Name__c = displayName,
                                                                                        Page_URL__c = pageURL,
                                                                                        Is_Active__c = true);
    if(isInsert) {                                  
      insert(test_SubNavigationItem);
    }
    return test_SubNavigationItem;
  }
    
    
  //insert Navigation Item
  public static ARM_Navigation_Item__c insertNavigationItemn(ARM_Retail_Function__c test_RetailFunction, String displayName, String pageURL, Boolean isInsert){
      
    //ARM_Retail_Function__c test_RetailFunction = insertRetailFunction('Joes Coffee' , true);
    ARM_Navigation_Item__c test_NavigationItem = new ARM_Navigation_Item__c ( Retail_Function__c = test_RetailFunction.Id,
                                                                              Display_Name__c = displayName,
                                                                              Page_URL__c = pageURL,
                                                                              Is_Active__c = true);    
    if(isInsert) {                                  
      insert(test_NavigationItem);
    }
    return test_NavigationItem;
  }
    
    
  //insert Retail function
  public static ARM_Retail_Function__c insertRetailFunction(String name, Boolean isInsert){
    ARM_Retail_Function__c test_RetailFunction = new ARM_Retail_Function__c (Name = name);
    
    if(isInsert) {                                  
      insert(test_RetailFunction);
    }
    return test_RetailFunction;
  }
    
  //insert User
  public static User insertUser(String profileName, Boolean isInsert){

    User testUser = new User();
    Profile p = [SELECT id from profile where name =: profileName ];

    testUser = new User(alias = 'testUser', email='standarduser' + randomNumber()  + '@testorg.com',
                             emailencodingkey='UTF-8', firstName='test user', lastname='Testing', languagelocalekey='en_US',
                             localesidkey='en_US', profileid = p.Id, timezonesidkey='America/Los_Angeles',
                             username='teststandarduser' + randomNumber() + '@testorg.com', IsActive=true,
                             CompanyName = 'test Company');
    
    if(isInsert) {                                  
      insert(testUser);
    }
    return testUser;
  }
  
  //insert Survey
  public static ARM_Survey__c insertSurvey(String name, Date startDate, Date endDate, String surveyType, Id accId, Boolean isInsert){

    ARM_Survey__c test_Assessment = new ARM_Survey__c (Name = name,
                                                       Active__c = true,
                                                       Start_Date__c = startDate,
                                                       End_Date__c = endDate,
                                                       Survey_Type_Editable__c= surveyType,
                                                       TDLinx_Acct_Level_E__c = accId);
    
    if(isInsert) {                                  
      insert(test_Assessment);
    }
    return test_Assessment;
  }
  
  //insert Survey Question
  public static ARM_Question__c insertSurveyQuestion(Id surveyId, String questionType, Boolean isInsert){

    ARM_Question__c test_SurveyQuestion = new ARM_Question__c (Survey__c = surveyId,
                                                               Question_Type__c = questionType );

    
    if(isInsert) {                                  
      insert(test_SurveyQuestion);
    }
    return test_SurveyQuestion;
  }
  
  
  //insert ARM Brand
  public static ARM_Brand__c insertBrand(String name, Boolean isInsert){
    ARM_Brand__c test_Brand = new ARM_Brand__c (Name = name);

    
    if(isInsert) {                                  
      insert(test_Brand);
    }
    return test_Brand;
  }
  
  
  // util method to get random number
  public static double randomNumber() {
    return Math.random();
  }
    
    

}