RetailDevGit/src/objects/ARM_Survey__c.object
<CustomObject>
    <description>Appirio Retail Management (ARM) Object</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Survey end date</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Survey start date</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Survey_Type_Editable__c</fullName>
        <description>Product surveys have a barcode scan and can loop through and answer questions about many products; Non-product surveys do NOT have a barcode scan.</description>
        <inlineHelpText>Product surveys have a barcode scan and can loop through and answer questions about many products; Non-product surveys do NOT have a barcode scan.</inlineHelpText>
        <label>Survey Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scan</fullName>
                </value>
                <value>
                    <fullName>Non Scan</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TDLinx_Acct_Level_E__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TDLinx Acct Level E</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ARM_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retailDev/src/classes/ARM_Survey_List_Controller.cls
/**=====================================================================
 * (c) 2017 Appirio - A Wipro Company, Inc
 * Name: ARM_IdentityController
 * Description: Controller class of lighting component ARM_Survey_List
 *              Controller class method returns Survey list based on 
 *              accountId
 * Created Date: Mar 07, 2017
 * Created By: Gaurav Gupta (Appirio - A Wipro Company)
 * 
 * Date Modified      Modified By                  Description of the update
 *  =====================================================================*/
public class ARM_Survey_List_Controller {
	private static final string SURVEY_TYPE_NON_SCAN = 'Non Scan';
    @auraEnabled
    public static List<Account> getAccounts(){
        List<Account> accountList = [SELECT Id, Name 
                                     FROM Account 
                                     LIMIT 999];
        return accountList;
    }
    
	@auraEnabled
    public static List<ARM_Survey__c> getSurveys(String accId){
        return [SELECT Id, Name 
                FROM ARM_Survey__c 
                WHERE Active__c = true 
                AND Start_Date__c <=: System.today() 
                AND End_Date__c >=: System.today() 
                AND Survey_Type_Editable__c = :SURVEY_TYPE_NON_SCAN 
                AND TDLinx_Acct_Level_E__c =: accId];
    } 
    
    
}