RetailDevGit/src/objects/ARM_Brand_Image__c.object
<CustomObject>
    <description>Appirio Retail Management (ARM) Object</description>
    <fields>
        <fullName>Image_Type__c</fullName>
        <inlineHelpText>Maximum Recommended Size (w*h) for:
Banner - 520px * 200px
Logo - 635px * 150px
Mobile Banner Logo - 200px * 150px  
Mobile Logo -  200px * 140px</inlineHelpText>
        <label>Image Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Banner</fullName>
                </value>
                <value>
                    <fullName>Logo</fullName>
                </value>
                <value>
                    <fullName>Mobile Logo</fullName>
                </value>
                <value>
                    <fullName>Mobile Banner Logo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>define that this image is active to be used by the side for parent brand</description>
        <inlineHelpText>If unchecked, the attached image will not be used in the site</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Retail_Function__c</fullName>
        <label>Retail Function</label>
        <referenceTo>ARM_Retail_Function__c</referenceTo>
        <relationshipLabel>Brand Images</relationshipLabel>
        <relationshipName>Brand_Images</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Brand Image</label>
    <nameField>
        <displayFormat>BI-{0000}</displayFormat>
        <label>Brand Images Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Images</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RetailDevGit/src/objects/ARM_Navigation_Item__c.object
<CustomObject>
    <description>Appirio Retail Management (ARM) Object. This object stores all the navigation items related to its parent functions.</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <inlineHelpText>eg. &quot;HOME&quot;. The name provided here will be the displayed name of navigation item on the site</inlineHelpText>
        <label>Display Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Defines the state of Navigation Item record</description>
        <inlineHelpText>If unchecked, the navigation item will not reflect in the site</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <inlineHelpText>Set the order of navigation - the navigation items in site will display according to the order defined here</inlineHelpText>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Page_URL__c</fullName>
        <inlineHelpText>Usually starts with /s/ where &apos;/s/&apos; being the home page. Note that name of pages is case sensitive.
eg. /s/mycases - in this case mycases page should be defined in community (lightning bolt) as a flexipage.</inlineHelpText>
        <label>Page-URL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Function__c</fullName>
        <label>Retail Function</label>
        <referenceTo>ARM_Retail_Function__c</referenceTo>
        <relationshipLabel>Navigation Items</relationshipLabel>
        <relationshipName>Navigation_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Navigation Item</label>
    <nameField>
        <displayFormat>NI-{00000}</displayFormat>
        <label>Navigation Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Navigation Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RetailDevGit/src/objects/ARM_Retail_Function__c.object
<CustomObject>
    <description>Appirio Retail Management (ARM) Object.
        This object stores the data for various retail functions used in salesforce bolt community cloud</description>
    <fields>
        <fullName>LogoBackgroundColor__c</fullName>
        <description>Define the background color for logo on header banner in your site</description>
        <inlineHelpText>CSS Legal Color Values are supported such as:
#ff0000 OR
rgb(255, 0, 0);   OR
rgba(255, 0, 0, 0.3);   OR
hsl(120, 100%, 50%);  OR
hsla(120, 100%, 50%, 0.3);</inlineHelpText>
        <label>Logo Background Color</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NavLinkColor__c</fullName>
        <inlineHelpText>CSS Legal Color Values are supported such as: 
#ff0000 OR 
rgb(255, 0, 0); OR 
rgba(255, 0, 0, 0.3); OR 
hsl(120, 100%, 50%); OR 
hsla(120, 100%, 50%, 0.3);</inlineHelpText>
        <label>Navigation Link Color</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NavLinkFontSize__c</fullName>
        <inlineHelpText>CSS units such as em, ex, %, px, cm, mm, in, pt, pc supported</inlineHelpText>
        <label>Navigation Link Font Size</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NavigationBackgroundColor__c</fullName>
        <description>Define the background color of your navigation in your site</description>
        <inlineHelpText>CSS Legal Color Values are supported such as: 
#ff0000 OR 
rgb(255, 0, 0); OR 
rgba(255, 0, 0, 0.3); OR 
hsl(120, 100%, 50%); OR 
hsla(120, 100%, 50%, 0.3);</inlineHelpText>
        <label>Navigation Background Color</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SelectedNavBackgroundColor__c</fullName>
        <inlineHelpText>CSS Legal Color Values are supported such as: 
#ff0000 OR 
rgb(255, 0, 0); OR 
rgba(255, 0, 0, 0.3); OR 
hsl(120, 100%, 50%); OR 
hsla(120, 100%, 50%, 0.3);</inlineHelpText>
        <label>Selected Navigation Background Color</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SelectedNavFontColor__c</fullName>
        <inlineHelpText>CSS Legal Color Values are supported such as: 
#ff0000 OR 
rgb(255, 0, 0); OR 
rgba(255, 0, 0, 0.3); OR 
hsl(120, 100%, 50%); OR 
hsla(120, 100%, 50%, 0.3);</inlineHelpText>
        <label>Selected Navigation Font Color</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubNavFontColor__c</fullName>
        <inlineHelpText>CSS Legal Color Values are supported such as: 
#ff0000 OR 
rgb(255, 0, 0); OR 
rgba(255, 0, 0, 0.3); OR 
hsl(120, 100%, 50%); OR 
hsla(120, 100%, 50%, 0.3);</inlineHelpText>
        <label>Sub Navigation Font Color</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubNavFontSize__c</fullName>
        <inlineHelpText>CSS units such as em, ex, %, px, cm, mm, in, pt, pc supported</inlineHelpText>
        <label>Sub Navigation Font Size</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubNavigationBackgroundColor__c</fullName>
        <description>Defines the background color of sub navigation</description>
        <inlineHelpText>CSS Legal Color Values are supported such as: 
#ff0000 OR 
rgb(255, 0, 0); OR 
rgba(255, 0, 0, 0.3); OR 
hsl(120, 100%, 50%); OR 
hsla(120, 100%, 50%, 0.3);</inlineHelpText>
        <label>Sub Navigation Background Color</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WelcomeTextColor__c</fullName>
        <inlineHelpText>CSS Legal Color Values are supported such as: 
#ff0000 OR 
rgb(255, 0, 0); OR 
rgba(255, 0, 0, 0.3); OR 
hsl(120, 100%, 50%); OR 
hsla(120, 100%, 50%, 0.3);</inlineHelpText>
        <label>Welcome Text Font Color</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Retail Function</label>
    <nameField>
        <label>Retail Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RetailDevGit/src/objects/ARM_Sub_Navigation_Item__c.object
<CustomObject>
    <description>Appirio Retail Management (ARM) Object</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <inlineHelpText>eg. &quot;HOME&quot;. The name provided here will be the displayed name of sub navigation item.</inlineHelpText>
        <label>Display Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Defines the state of Sub Navigation Item record</description>
        <inlineHelpText>If unchecked, this will not get reflected in the site</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Navigation_Item__c</fullName>
        <label>Navigation Item</label>
        <referenceTo>ARM_Navigation_Item__c</referenceTo>
        <relationshipLabel>Sub Navigation Items</relationshipLabel>
        <relationshipName>Sub_Navigation_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <inlineHelpText>The order in which the sub-navigation item will display on the site</inlineHelpText>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Page_URL__c</fullName>
        <inlineHelpText>Usually starts with /s/ where &apos;/s/&apos; being the home page. Note that name of pages is case sensitive.
eg. /s/mycases - in this case mycases page should be defined in community (lightning bolt) as a flexipage.</inlineHelpText>
        <label>Page-URL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Sub Navigation Item</label>
    <nameField>
        <displayFormat>SNI-{0000}</displayFormat>
        <label>Sub Navigation Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sub Navigation Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RetailDevGit/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ARM_physicalDeliveryOfficeName__c</fullName>
        <label>Office Location</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

RetailDevGit/src/classes/ARM_TemplateController.cls
/**=====================================================================
 * (c) 2017 Appirio - A Wipro Company, Inc
 * Name: ARM_TemplateController
 * Description: Controller class of lighting component ARM_Template
 * Created Date: Mar 07, 2017
 * Created By: Gaurav Gupta (Appirio - A Wipro Company)
 * 
 * Date Modified      Modified By                  Description of the update
 *  =====================================================================*/
public without sharing class ARM_TemplateController {
    private static final string DESIGNATED_CONTACT = 'Designated Contact';
    @AuraEnabled
    public static User getCurrentUser() {
        User u = [SELECT id, FirstName, LastName, Name, FullPhotoUrl  
                  FROM User 
                  WHERE id = :UserInfo.getUserId() 
                  LIMIT 1];
        return u;
    }
   
    @AuraEnabled 
   public static List<ARM_Navigation_Item__c> getNavigationList() {
        String officeLocation = getOfficeLocation();
        return [SELECT Id, Display_Name__c, 
                  Page_URL__c, Order__c, 
                (SELECT Id 
                 FROM Attachments order by CreatedDate desc LIMIT 1)
                  FROM ARM_Navigation_Item__c 
                  WHERE Retail_Function__r.Name = :officeLocation
                  AND Is_Active__c = true
                  ORDER BY ORDER__c ASC];
        
   }
    
   @AuraEnabled 
   public static List<ARM_Sub_Navigation_Item__c> getSubNavigationList(String navigationId) {
       System.debug('navigationId::::' + navigationId);
       if(!String.isBlank(navigationId)){
          return [SELECT Id, Display_Name__c, 
                  Page_URL__c, Order__c, 
                   (SELECT Id 
                 FROM Attachments order by CreatedDate desc LIMIT 1) 
                  FROM ARM_Sub_Navigation_Item__c 
                  WHERE Navigation_Item__c = :navigationId
                  AND Is_Active__c = true
                  ORDER BY ORDER__c ASC];
       }else{
          return new List<ARM_Sub_Navigation_Item__c>();  
       }
   }  
   
   @AuraEnabled 
   public static List<ARM_Navigation_Item__c> getCurrentNavigationItemId(String pageURL) {
       
       String officeLocation = getOfficeLocation();
       List<ARM_Navigation_Item__c> lst = [SELECT Id, Display_Name__c  
                  FROM ARM_Navigation_Item__c 
                  WHERE Page_URL__c = :pageURL
                  AND Retail_Function__r.Name = : officeLocation];
       
        
       return lst;
   }
    
    @AuraEnabled
    public static Integer getNumberRestaurants() {
        /*  Retrieve the number of Accounts where current user is a Designated Contact contact role */
        User u = [SELECT ContactId 
                  FROM User 
                  WHERE id = :UserInfo.getUserId() 
                  LIMIT 1];
        
        List<AccountContactRole> AccountContactRoles = [ 
            SELECT AccountId 
            FROM AccountContactRole
            WHERE ContactId = :u.ContactId
            AND Role = :DESIGNATED_CONTACT
        ];
        return AccountContactRoles.size();
    }
    
    @AuraEnabled
    public static String getOfficeLocation() {
        /*  Retrieve the Account where current user is a Designated Contact contact role */
        User u = [ SELECT ARM_physicalDeliveryOfficeName__c 
                  FROM User 
                  WHERE id = :UserInfo.getUserId() 
                  LIMIT 1];
        return u.ARM_physicalDeliveryOfficeName__c ;
    }
    
    @AuraEnabled
    public static ARM_Retail_Function__c getBrandAttributes() {
        String officeLocation = getOfficeLocation();
        
        ARM_Retail_Function__c retailFunction = new ARM_Retail_Function__c( SubNavigationBackgroundColor__c = '',
                                                 NavigationBackgroundColor__c = '',
                                                 LogoBackgroundColor__c = '',
                                                 SelectedNavBackgroundColor__c = '',
                                                 SelectedNavFontColor__c = '',
                                                 NavLinkFontSize__c = '',
                                                 NavLinkColor__c = '',
                                                 SubNavFontSize__c = '',
                                                 SubNavFontColor__c = '', 
                                                 WelcomeTextColor__c = '');
        if(!String.isBlank(officeLocation)){
            
            List<ARM_Retail_Function__c> lst = [SELECT id , 
                  SubNavigationBackgroundColor__c, 
                  NavigationBackgroundColor__c,
                  LogoBackgroundColor__c,
                  SelectedNavBackgroundColor__c,
                  SelectedNavFontColor__c, 
                  NavLinkFontSize__c,
                  NavLinkColor__c,
                  SubNavFontSize__c,
                  SubNavFontColor__c,
                  WelcomeTextColor__c
                  FROM ARM_Retail_Function__c 
                  WHERE Name = : officeLocation];
            if(!lst.isEmpty()){
               retailFunction = lst[0];
            }
            
        }
            
        return retailFunction;
    }
    
    @AuraEnabled
    public static String getBrandImageURL() {
        
        
        String officeLocation = getOfficeLocation();
        
        String imageUrl = '/s.gif';
        if(officeLocation != NULL){
            
            List<ARM_Brand_Image__c> lst = [SELECT id , (Select id from attachments)
                  FROM ARM_Brand_Image__c 
                  WHERE Is_Active__c = true
                  AND Image_Type__c = 'Logo'
                  AND Retail_Function__r.Name = : officeLocation];
            if(!lst.isEmpty() && !lst[0].attachments.isEmpty()){
               imageUrl = '/servlet/servlet.FileDownload?file=' + lst[0].attachments[0].id;
            }
            
        }
            
        return imageUrl;
        
    }
    
    @AuraEnabled
    public static String getBrandMobileImageURL() {
        
        
        String officeLocation = getOfficeLocation();
        
        String imageUrl = '/s.gif';
        if(officeLocation != NULL){
            
            List<ARM_Brand_Image__c> lst = [SELECT id , (Select id from attachments)
                  FROM ARM_Brand_Image__c 
                  WHERE Is_Active__c = true
                  AND Image_Type__c = 'Mobile Logo'
                  AND Retail_Function__r.Name = : officeLocation];
            if(!lst.isEmpty() && !lst[0].attachments.isEmpty()){
               imageUrl = '/servlet/servlet.FileDownload?file=' + lst[0].attachments[0].id;
            }
            
        }
            
        return imageUrl;
        
    }
    
    
    @AuraEnabled
    public static String getBannerImageURL() {
        String officeLocation = getOfficeLocation();
        
        String imageUrl = '/s.gif';
        if(officeLocation != NULL){
            
            List<ARM_Brand_Image__c> lst = [SELECT id , (Select id from attachments)
                  FROM ARM_Brand_Image__c 
                  WHERE Is_Active__c = true
                  AND Image_Type__c = 'Banner'
                  AND Retail_Function__r.Name = : officeLocation];
            if(!lst.isEmpty() && !lst[0].attachments.isEmpty()){
               imageUrl = '/servlet/servlet.FileDownload?file=' + lst[0].attachments[0].id;
               
            }
            
        }
            
        return imageUrl;
    }
    
    @AuraEnabled
    public static String getBannerMobileLogoURL() {
        String officeLocation = getOfficeLocation();
        
        String imageUrl = '/s.gif';
        if(officeLocation != NULL){
            
            List<ARM_Brand_Image__c> lst = [SELECT id , (Select id from attachments)
                  FROM ARM_Brand_Image__c 
                  WHERE Is_Active__c = true
                  AND Image_Type__c = 'Mobile Banner Logo'
                  AND Retail_Function__r.Name = : officeLocation];
            if(!lst.isEmpty() && !lst[0].attachments.isEmpty()){
               imageUrl = '/servlet/servlet.FileDownload?file=' + lst[0].attachments[0].id;
               
            }
            
        }
            
        return imageUrl;
    }
}