RetailDevGit/src/objects/ARM_Question__c.object
<CustomObject>
    <description>Appirio Retail Management (ARM) Object</description>
    <fields>
        <fullName>Answer_Options__c</fullName>
        <defaultValue>&quot;YES, NO&quot;</defaultValue>
        <description>Options for picklist question types</description>
        <inlineHelpText>Enter comma separated values that should show as options in the picklist</inlineHelpText>
        <label>Answer Options</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Conditional_Answer__c</fullName>
        <description>If this question is related to a parent question, this is the answer that will lead to this question being displayed in the survey.</description>
        <inlineHelpText>If this question is related to a parent question, this is the answer that will lead to this question being displayed in the survey.</inlineHelpText>
        <label>Conditional Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Include_None_of_the_Above__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For Picklists and Multi-Select picklists, we want an option to add &apos;None of the Above&apos; to the list where appropriate</description>
        <inlineHelpText>Include if you want the user to have the option to select None of the Above</inlineHelpText>
        <label>Include &apos;None of the Above&apos;</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Include_Photos__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include Photos</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Conditional questions have a PARENT question.   The parent question is answered and if the answer matches, then this child question is asked.</description>
        <inlineHelpText>Conditional questions have a PARENT question.   The parent question is answered and if the answer matches, then this child question is asked.</inlineHelpText>
        <label>Parent Question</label>
        <referenceTo>ARM_Question__c</referenceTo>
        <relationshipLabel>Conditional Questions</relationshipLabel>
        <relationshipName>ARM_Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <label>Question Text</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ARM Survey Question</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RetailDevGit/src/objects/ARM_Survey__c.object
<CustomObject>
    <description>Appirio Retail Management (ARM) Object</description>
    <label>Assessment</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RetailDevGit/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ARM_physicalDeliveryOfficeName__c</fullName>
        <label>Office Location</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

RetailDevGit/src/classes/ARM_Survey_Question_DetailControllerTest.cls
/**=====================================================================
 * (c) 2017 Appirio - A Wipro Company, Inc
 * Name: ARM_Survey_Question_Detail_ControllerTest
 * Description: Includes all test methods to perform unit test over ARM_TemplateController class.
 * Created Date: Mar 07, 2017
 * Created By: Gaurav Gupta (Appirio - A Wipro Company)
 * 
 * Date Modified      Modified By                  Description of the update
 *  =====================================================================*/

@isTest
private class ARM_Survey_Question_DetailControllerTest{
    private final static string PROFILE_SYS_ADMIN = 'System Administrator';
    private static User sysAdmin;
    private static final string SURVEY_TYPE_NON_SCAN = 'Non Scan';

    
 private static testmethod void testSurveyQuestionController(){
       
       sysAdmin= getSysAdminUser();
       System.runAs(sysAdmin){
        ARM_Survey__c rF = [select id from ARM_Survey__c LIMIT 1];  
         test.startTest();
            
            String jsonQuestions = ARM_Survey_Question_Detail_Controller.getQuestions(rF.id);
            ARM_Survey_Question_Detail_Controller.ResultWrapper answersToWrapper = (ARM_Survey_Question_Detail_Controller.ResultWrapper) JSON.DeSerialize(jsonQuestions,ARM_Survey_Question_Detail_Controller.ResultWrapper.class);
            Map<String,ARM_Survey_Question_Detail_Controller.QuestionWrapper> questions = (Map<String,ARM_Survey_Question_Detail_Controller.QuestionWrapper>) answersToWrapper.parentQuestions;
                    for(String questionId : questions.keySet()){
                        questions.get(questionId).isDone = true;
                        questions.get(questionId).answer = '1';
                        if(questions.get(questionId).question.Include_Photos__c == true){
                            list<string> imgURLS = new list<string>();
                            imgURLS.add('/test');
                            questions.get(questionId).imageURLs = imgURLS ;
                        }
                    }
            String jsonQuestionsSerialize = JSON.serialize(answersToWrapper);
            system.assertEquals('SUCCESS',ARM_Survey_Question_Detail_Controller.SaveSurveyResult(jsonQuestionsSerialize) ,'Error occured while saving the file');
            Id parentId = (new list<string>(questions.keySet()) )[0];
            Id fileId = ARM_Survey_Question_Detail_Controller.saveTheChunk(parentId, 'test','test','jpeg', '', true);
            system.assertEquals(fileId, ARM_Survey_Question_Detail_Controller.saveTheChunk(parentId, 'test','test','jpeg',fileId, true) ,'Incorrect file id');
            system.assert(ARM_Survey_Question_Detail_Controller.saveTheFile(parentId,'test','test','jpeg')!=null ,'Attachment can not be null');
         test.stopTest();
         

         
       }
 }
 

  private static User getSysAdminUser(){
      User admin=[Select Id from user where firstName='test user' AND lastname='Testing'];
      return admin;
  }
 
    @testSetup
    private static void createTestData(){
        User testUser = ARM_Retail_Test_Utils.insertUser(PROFILE_SYS_ADMIN, false);
        testUser.ARM_physicalDeliveryOfficeName__c = 'Joes Coffee' ;
        insert testUser;
        
        Account a = ARM_Retail_Test_Utils.insertAccount(true);
        ARM_Survey__c rF = ARM_Retail_Test_Utils.insertSurvey('Mini Survey', system.today(), system.today(), SURVEY_TYPE_NON_SCAN , a.id, true);
        ARM_Question__c parentQuestion = ARM_Retail_Test_Utils.insertSurveyQuestion(rF.Id , 'Count' , false);
        parentQuestion.Answer_Options__c = '[{"valueBrandId":"","value":"Yes","score":"0","goalScore":"0"},{"valueBrandId":"","value":"No","score":"0","goalScore":"0"}]' ;
        parentQuestion.Question_Text__c = 'How many sessions were held this week?';
        insert parentQuestion;   
        
        ARM_Question__c question = ARM_Retail_Test_Utils.insertSurveyQuestion(rF.Id , 'Text' , false);
        question.Answer_Options__c = '[{"valueBrandId":"","value":"Yes","score":"0","goalScore":"0"},{"valueBrandId":"","value":"No","score":"0","goalScore":"0"}]' ;
        question.Question_Text__c = 'Satisfied with trainer?';
        question.Parent_Question__c = parentQuestion.id;
        question.Conditional_Answer__c = 'Yes';
        question.Include_None_of_the_Above__c = true;
        question.Include_Photos__c = true;
        insert question;      

        ARM_Question__c selectQuestion = ARM_Retail_Test_Utils.insertSurveyQuestion(rF.Id , 'Select' , false);
        selectQuestion.Answer_Options__c = '[{"valueBrandId":"","value":"Yes","score":"0","goalScore":"0"},{"valueBrandId":"","value":"No","score":"0","goalScore":"0"}]' ;
        selectQuestion.Question_Text__c = 'Want to join?';
        selectQuestion.Parent_Question__c = parentQuestion.id;
        selectQuestion.Include_None_of_the_Above__c = true;
        insert selectQuestion;     

        

    }
    

}