RetailDevGit/src/objects/ARM_Brand__c.object
<CustomObject>
    <description>Appirio Retail Management (ARM) Object</description>
    <fields>
        <fullName>Hierarchy_Code__c</fullName>
        <externalId>true</externalId>
        <label>Full Hierarchy Code</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <formula>IF( ISBLANK(Hierarchy_Code__c), &quot;NH&quot;,
IF(  ISPICKVAL( Brand_Type__c , &quot;Classification&quot;), &quot;L1&quot;,  
        IF(  ISPICKVAL( Brand_Type__c , &quot;Group / Type&quot;), &quot;L2&quot;, 
             IF(  ISPICKVAL( Brand_Type__c , &quot;Brand&quot;), &quot;L3&quot;, 
            	  IF(  ISPICKVAL( Brand_Type__c , &quot;Brand Variant&quot;), &quot;L4&quot;, 
                	IF(  ISPICKVAL( Brand_Type__c , &quot;Individual Variant&quot;), &quot;L5&quot;, 
			     IF(  ISPICKVAL( Brand_Type__c , &quot;Volume&quot;), &quot;L6&quot;, &quot;L7&quot;)))))))</formula>
        <label>Level #</label>
        <type>Text</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ARM Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RetailDevGit/src/objects/ARM_Question__c.object
<CustomObject>
    <description>Appirio Retail Management (ARM) Object</description>
    <fields>
        <fullName>Answer_Options__c</fullName>
        <defaultValue>&quot;YES, NO&quot;</defaultValue>
        <description>Options for picklist question types</description>
        <inlineHelpText>Enter comma separated values that should show as options in the picklist</inlineHelpText>
        <label>Answer Options</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Conditional_Answer_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Conditional Answer Brand</label>
        <referenceTo>ARM_Brand__c</referenceTo>
        <relationshipLabel>Survey Question (Conditional Answer Brand)</relationshipLabel>
        <relationshipName>Survey_Question1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Conditional_Answer__c</fullName>
        <description>If this question is related to a parent question, this is the answer that will lead to this question being displayed in the survey.</description>
        <inlineHelpText>If this question is related to a parent question, this is the answer that will lead to this question being displayed in the survey.</inlineHelpText>
        <label>Conditional Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal Brand</label>
        <referenceTo>ARM_Brand__c</referenceTo>
        <relationshipLabel>ARM Survey Question</relationshipLabel>
        <relationshipName>ARM_Survey_Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Goal_Name__c</fullName>
        <label>Goal Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal_Type__c</fullName>
        <label>Goal Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Display</fullName>
                </value>
                <value>
                    <fullName>Feature</fullName>
                </value>
                <value>
                    <fullName>Distribution</fullName>
                </value>
                <value>
                    <fullName>Point of Distribution</fullName>
                </value>
                <value>
                    <fullName>Shelf Sets</fullName>
                </value>
                <value>
                    <fullName>Cold Box</fullName>
                </value>
                <value>
                    <fullName>Ad Execution</fullName>
                </value>
                <value>
                    <fullName>QD / Volume</fullName>
                </value>
                <value>
                    <fullName>Menu</fullName>
                </value>
                <value>
                    <fullName>Sampling</fullName>
                </value>
                <value>
                    <fullName>Staff Training</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Vendor Quality</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Include_None_of_the_Above__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For Picklists and Multi-Select picklists, we want an option to add &apos;None of the Above&apos; to the list where appropriate</description>
        <inlineHelpText>Include if you want the user to have the option to select None of the Above</inlineHelpText>
        <label>Include &apos;None of the Above&apos;</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Include_Photos__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include Photos</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Goal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Goal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Label_for_Add_l_Comments__c</fullName>
        <description>If we are going to capture additional comments for this question, then this is the label that should be displayed above the comments textarea.</description>
        <inlineHelpText>If we are going to capture additional comments for this question, then this is the label that should be displayed above the comments textarea.</inlineHelpText>
        <label>Label for Add&apos;l Comments</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Goal_Score__c</fullName>
        <description>Max goal score total</description>
        <label>Max Goal Score</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Score__c</fullName>
        <description>The max possible score for this question.  Single-select picklist will be the MAX value of all of the answer options and multi-select picklist will be the SUM of all of the answer scores.</description>
        <inlineHelpText>The max possible score for this question.  Single-select picklist will be the MAX value of all of the answer options and multi-select picklist will be the SUM of all of the answer scores.</inlineHelpText>
        <label>Max Score</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NEXT_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The next question in the screen flow if there are no conditional questions OR if all conditional questions are complete.</description>
        <label>NEXT Question</label>
        <referenceTo>ARM_Question__c</referenceTo>
        <relationshipLabel>Previous Questions</relationshipLabel>
        <relationshipName>Follows_these_questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Conditional questions have a PARENT question.   The parent question is answered and if the answer matches, then this child question is asked.</description>
        <inlineHelpText>Conditional questions have a PARENT question.   The parent question is answered and if the answer matches, then this child question is asked.</inlineHelpText>
        <label>Parent Question</label>
        <referenceTo>ARM_Question__c</referenceTo>
        <relationshipLabel>Conditional Questions</relationshipLabel>
        <relationshipName>ARM_Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Number__c</fullName>
        <description>The nested number of the question</description>
        <label>Question Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <label>Question Text</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Count</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Select</fullName>
                </value>
                <value>
                    <fullName>Multi-Select</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Require_Photos__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Require Photos</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <description>Survey header object</description>
        <inlineHelpText>Survey header object</inlineHelpText>
        <label>Survey</label>
        <referenceTo>ARM_Survey__c</referenceTo>
        <relationshipName>ARM_Question</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ARM Survey Question</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RetailDevGit/src/objects/ARM_Survey__c.object
<CustomObject>
    <description>Appirio Retail Management (ARM) Object</description>
    <fields>
        <fullName>First_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The very first question in the survey.  Note that this is NOT relevant for product-based surveys that always start with the barcode scan.</description>
        <inlineHelpText>The very first question in the survey.  Note that this is NOT relevant for product-based surveys that always start with the barcode scan.</inlineHelpText>
        <label>First Question</label>
        <referenceTo>ARM_Question__c</referenceTo>
        <relationshipName>First_Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RetailDevGit/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ARM_physicalDeliveryOfficeName__c</fullName>
        <label>Office Location</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

RetailDevGit/src/classes/ARM_SurveyEditorControllerTest.cls
/**=====================================================================
 * (c) 2017 Appirio - A Wipro Company, Inc
 * Name: ARM_SurveyEditorControllerTest
 * Description: Includes all test methods to perform unit test over ARM_SurveyEditorController class.
 * Created Date: Mar 08, 2017
 * Created By: Gaurav Gupta (Appirio - A Wipro Company)
 * 
 * Date Modified      Modified By                  Description of the update
 *  =====================================================================*/

@isTest
private class ARM_SurveyEditorControllerTest{
    private final static string PROFILE_SYS_ADMIN = 'System Administrator';
    private static User sysAdmin;
    private static final string SURVEY_TYPE_NON_SCAN = 'Non Scan';

    
 private static testmethod void testSurveyQuestionController(){
       
       sysAdmin= getSysAdminUser();
       System.runAs(sysAdmin){
        ARM_Survey__c rF = [select id from ARM_Survey__c LIMIT 1];  
         test.startTest();
            ARM_SurveyEditorController aSE = new ARM_SurveyEditorController(new ApexPages.StandardController(rF));
            system.assert(ARM_SurveyEditorController.getSurvey(rF.id)!=null , 'No survey result is retuned');
            ARM_SurveyEditorController.SurveyQuestion innerQuestionClass= new ARM_SurveyEditorController.SurveyQuestion();
            
            ARM_Question__c quesId = [SELECT Id,
                                            Survey__c,
                                            NEXT_Question__c,
                                            Parent_Question__c,
                                            Name,
                                            Conditional_Answer__c,
                                            Conditional_Answer_Brand__c,
                                            Question_Text__c,
                                            Question_Type__c,
                                            Answer_Options__c,
                                            Label_for_Add_l_Comments__c,
                                            CreatedBy.Alias,CreatedDate ,
                                            LastModifiedDate,
                                            Question_Number__c,
                                            Include_None_of_the_Above__c,
                                            Include_Photos__c,
                                            Require_Photos__c,
                                            LastModifiedBy.Alias,
                                            Max_Score__c,
                                            Max_Goal_Score__c,
                                            Is_Goal__c,
                                            Goal_Name__c,
                                            Goal_Type__c,
                                            Goal_Brand__r.level__c,
                                            Goal_Brand__r.id
                                    FROM ARM_Question__c where Parent_Question__c!=null 
                                    //AND  Is_Goal__c = true
                                    LIMIT 1];
            
            ARM_SurveyEditorController.SurveyQuestion innerQuestionClassWithQues= new ARM_SurveyEditorController.SurveyQuestion(quesId);
            ARM_Question__c question = innerQuestionClassWithQues.getSObject();
            system.assert(ARM_SurveyEditorController.upsertQuestion(innerQuestionClassWithQues)!=null , 'Question could not get updated successfully');
            ARM_SurveyEditorController.setFirstQuestion(quesId.id);
            //catching exception in case of wrong qiestion Id
            try{
                ARM_SurveyEditorController.setFirstQuestion('invalidId');
            }catch(exception e){
                String error = e.getMessage();
                system.assert(true == error.contains('Unexpected error: Question not found') , e.getMessage() );
            }
            ARM_SurveyEditorController.removeQuestion(quesId.id);
            //catching exception for In-valid question
            try{
                ARM_SurveyEditorController.upsertQuestion(null);
            }catch(exception e){
                String error = e.getMessage();
                system.assert(true == error.contains('Need a valid question object') , e.getMessage() );
            }
            
            
            ARM_SurveyEditorController.getBrands('NHtest' , 'NH' , '1');
            ARM_SurveyEditorController.searchBrands('NHtest' , '11' );
            aSE.getGoalTypes();
         test.stopTest();
         

         
       }
 }
 

  private static User getSysAdminUser(){
      User admin=[Select Id from user where firstName='test user' AND lastname='Testing'];
      return admin;
  }
 
    @testSetup
    private static void createTestData(){
        User testUser = ARM_Retail_Test_Utils.insertUser(PROFILE_SYS_ADMIN, false);
        testUser.ARM_physicalDeliveryOfficeName__c = 'Joes Coffee' ;
        insert testUser;
        
        Account a = ARM_Retail_Test_Utils.insertAccount(true);
        ARM_Survey__c rF = ARM_Retail_Test_Utils.insertSurvey('Mini Survey', system.today(), system.today(), SURVEY_TYPE_NON_SCAN , a.id, true);
        ARM_Question__c parentQuestion = ARM_Retail_Test_Utils.insertSurveyQuestion(rF.Id , 'Count' , false);
        parentQuestion.Answer_Options__c = '[{"valueBrandId":"","value":"Yes","score":"0","goalScore":"0"},{"valueBrandId":"","value":"No","score":"0","goalScore":"0"}]' ;
        parentQuestion.Question_Text__c = 'How many sessions were held this week?';
        parentQuestion.Is_Goal__c = true;
        insert parentQuestion;  
        
        rF.First_Question__c = parentQuestion.id;
        update rF;
        
        ARM_Question__c question = ARM_Retail_Test_Utils.insertSurveyQuestion(rF.Id , 'Text' , false);
        question.Answer_Options__c = '[{"valueBrandId":"","value":"Yes","score":"0","goalScore":"0"},{"valueBrandId":"","value":"No","score":"0","goalScore":"0"}]' ;
        question.Question_Text__c = 'Satisfied with trainer?';
        question.Parent_Question__c = parentQuestion.id;
        question.Conditional_Answer__c = 'Yes';
        //question.Is_Goal__c = true;
        question.Include_None_of_the_Above__c = true;
        question.Include_Photos__c = true;
        insert question;
        
        parentQuestion.NEXT_Question__c = question.id;
        update parentQuestion;

        ARM_Question__c selectQuestion = ARM_Retail_Test_Utils.insertSurveyQuestion(rF.Id , 'Select' , false);
        selectQuestion.Answer_Options__c = '[{"valueBrandId":"","value":"Yes","score":"0","goalScore":"0"},{"valueBrandId":"","value":"No","score":"0","goalScore":"0"}]' ;
        selectQuestion.Question_Text__c = 'Want to join?';
        selectQuestion.Parent_Question__c = parentQuestion.id;
        //selectQuestion.Is_Goal__c = true;
        selectQuestion.Include_None_of_the_Above__c = true;
        insert selectQuestion;     
        
        
        ARM_Brand__c test_Brand = ARM_Retail_Test_Utils.insertBrand('NHtest' , false);
        test_Brand.Hierarchy_Code__c = '';
        insert test_Brand;

        

    }
    

}