RetailDevGit/src/objects/ARM_Brand_Image__c.object
<CustomObject>
    <description>Appirio Retail Management (ARM) Object</description>
    <fields>
        <fullName>Image_Type__c</fullName>
        <inlineHelpText>Maximum Recommended Size (w*h) for:
Banner - 520px * 200px
Logo - 635px * 150px
Mobile Banner Logo - 200px * 150px  
Mobile Logo -  200px * 140px</inlineHelpText>
        <label>Image Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Banner</fullName>
                </value>
                <value>
                    <fullName>Logo</fullName>
                </value>
                <value>
                    <fullName>Mobile Logo</fullName>
                </value>
                <value>
                    <fullName>Mobile Banner Logo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Brand Image</label>
    <nameField>
        <displayFormat>BI-{0000}</displayFormat>
        <label>Brand Images Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Images</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RetailDevGit/src/objects/ARM_Navigation_Item__c.object
<CustomObject>
    <description>Appirio Retail Management (ARM) Object. This object stores all the navigation items related to its parent functions.</description>
    <label>Navigation Item</label>
    <nameField>
        <displayFormat>NI-{00000}</displayFormat>
        <label>Navigation Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Navigation Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RetailDevGit/src/objects/ARM_Retail_Function__c.object
<CustomObject>
    <description>Appirio Retail Management (ARM) Object.
        This object stores the data for various retail functions used in salesforce bolt community cloud</description>
    <fields>
        <fullName>Franchise_title__c</fullName>
        <label>Franchise Title</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Retail Function</label>
    <nameField>
        <label>Retail Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RetailDevGit/src/objects/ARM_Sub_Navigation_Item__c.object
<CustomObject>
    <description>Appirio Retail Management (ARM) Object</description>
    <label>Sub Navigation Item</label>
    <nameField>
        <displayFormat>SNI-{0000}</displayFormat>
        <label>Sub Navigation Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sub Navigation Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RetailDevGit/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ARM_physicalDeliveryOfficeName__c</fullName>
        <label>Office Location</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

retailDev/src/classes/ARM_TemplateControllerTest.cls
/**=====================================================================
 * (c) 2017 Appirio - A Wipro Company, Inc
 * Name: ARM_TemplateControllerTest
 * Description: Includes all test methods to perform unit test over ARM_TemplateController class.
 * Created Date: Mar 07, 2017
 * Created By: Gaurav Gupta (Appirio - A Wipro Company)
 * 
 * Date Modified      Modified By                  Description of the update
 *  =====================================================================*/

@isTest
private class ARM_TemplateControllerTest{
    private final static string PROFILE_SYS_ADMIN = 'System Administrator';
    private static final string DESIGNATED_CONTACT = 'Designated Contact';
    private static User sysAdmin;

 private static testmethod void testTemplateController(){
       
       sysAdmin= getSysAdminUser();
       System.runAs(sysAdmin){
           
         test.startTest();
            User u = ARM_TemplateController.getCurrentUser();
            system.assertEquals(sysAdmin.id, u.id, 'System admin user is expected. Received something else.');

            list<ARM_Navigation_Item__c> lstNavigationItems = ARM_TemplateController.getNavigationList();
            system.assert(true ,lstNavigationItems.size()>0);
            system.assertEquals(lstNavigationItems[0].Attachments.size() , 1 , 'Atleast one attachmnet should be found');

            list<ARM_Sub_Navigation_Item__c> lstSubNavs =  ARM_TemplateController.getSubNavigationList(lstNavigationItems[0].id);
            system.assertEquals(lstSubNavs[0].Attachments.size() , 1 , 'Atleast one attachmnet should be found');

            list<ARM_Navigation_Item__c> navItemList = ARM_TemplateController.getCurrentNavigationItemId('/s/dashboard');
            system.assertEquals(navItemList[0].id, lstNavigationItems[0].id , 'Incorrect navigation item is retrieved');
            
            ARM_Retail_Function__c rF = ARM_TemplateController.getBrandAttributes();
            rF = [select name from ARM_Retail_Function__c LIMIT 1] ;
            system.assertEquals(rF.name, 'Joes Coffee' , 'Incorrect retail function is retrieved');

            system.assert(ARM_TemplateController.getNumberRestaurants() == 0, 'Number of Accounts where current user is a Designated Contact should be 0 as the logged in user is System Admin ');
            system.assert(ARM_TemplateController.getBrandImageURL() != '/s.gif', 'Default logo URL is not as expected');
            system.assert(ARM_TemplateController.getBrandMobileImageURL() != '/s.gif', 'Default mobile logo URL is not as expected');
            system.assert(ARM_TemplateController.getBannerImageURL() != '/s.gif', 'Default banner URL is not as expected' );
            system.assert(ARM_TemplateController.getBannerMobileLogoURL() != '/s.gif', 'Default mobile banner URL is not as expected' );

            
         test.stopTest();
         

         
       }
 }
    

  private static User getSysAdminUser(){
      User admin=[Select Id from user where firstName='test user' AND lastname='Testing'];
      return admin;
  }
  
    @testSetup
    private static void createTestData(){
        Account a = ARM_Retail_Test_Utils.insertAccount(true);
        Contact c = ARM_Retail_Test_Utils.insertContact(a.id , true);
        
        User testUser = ARM_Retail_Test_Utils.insertUser(PROFILE_SYS_ADMIN, false);
        testUser.ARM_physicalDeliveryOfficeName__c = 'Joes Coffee' ;
        insert testUser;
        
        ARM_Retail_Function__c test_RetailFunction = ARM_Retail_Test_Utils.insertRetailFunction('Joes Coffee' , false);
        test_RetailFunction.Franchise_title__c = 'Stores';
        insert test_RetailFunction ;
        
        ARM_Navigation_Item__c test_NavigationItem = ARM_Retail_Test_Utils.insertNavigationItemn(test_RetailFunction, 'HOME', '/s/dashboard', true);
        ARM_Sub_Navigation_Item__c test_SubNavigationItem = ARM_Retail_Test_Utils.insertSubNavigationItemn(test_NavigationItem, 'Advocacy', '/s/advocacy-center', true);
        
        list<ARM_Brand_Image__c> lstBrandImages = new list<ARM_Brand_Image__c>();
        lstBrandImages.add(ARM_Retail_Test_Utils.insertAccountContactRole(test_RetailFunction, 'Logo', false));
        lstBrandImages.add(ARM_Retail_Test_Utils.insertAccountContactRole(test_RetailFunction, 'Mobile Logo', false));
        lstBrandImages.add(ARM_Retail_Test_Utils.insertAccountContactRole(test_RetailFunction, 'Banner', false));
        lstBrandImages.add(ARM_Retail_Test_Utils.insertAccountContactRole(test_RetailFunction, 'Mobile Banner Logo', false));
        insert lstBrandImages;
        
        AccountContactRole accountRole = ARM_Retail_Test_Utils.insertAccountContactRole(a.id, c.id, false);
        accountRole.role = DESIGNATED_CONTACT;
        insert accountRole;
        
        list<Attachment> lstBrandImagesAttachment = new  list<Attachment>();
        for(ARM_Brand_Image__c brandImage : lstBrandImages){
            lstBrandImagesAttachment.add( ARM_Retail_Test_Utils.insertAttachment(brandImage.id,brandImage.Image_Type__c , false ) );
        }
        lstBrandImagesAttachment.add( ARM_Retail_Test_Utils.insertAttachment(test_NavigationItem.id,'Navigation attachment' , false ) );
        lstBrandImagesAttachment.add( ARM_Retail_Test_Utils.insertAttachment(test_SubNavigationItem.id,'Sub-Navigation attachment' , false ) );
        insert lstBrandImagesAttachment;
    }
    

}